### ISSUE TITLE
Unable to find dependency on Maven Central

### ISSUE THREAD

**Issue by amucunguzi** [magneticflux-/ortools-java#21]
I am trying to import `ortools-natives-all` into my project as follow:

```
    <dependency>
            <groupId>com.skaggsm.ortools</groupId>
            <artifactId>ortools-natives-all</artifactId>
            <version>7.8.7960</version>
     </dependency>

```
But I keep getting "Could not find artifact com.skaggsm.ortools:ortools-natives-all:jar:7.8.7960 in central (https://repo.maven.apache.org/maven2)". 

I cannot tell what I am doing wrong. Tried several options to load the package.

**Comment by magneticflux-** [comment]
The package is not on Maven Central, only in the JCenter repository (a superset of Maven Central). It is available in Gradle by using `jcenter()` in the dependency block. More information on why it's hosted there instead of Maven Central [here](https://blog.bintray.com/2014/02/11/bintray-as-pain-free-gateway-to-maven-central/).
